config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
  }
  devise_for :customers, controllers: {
    sessions: 'public/sessions',
    passwords: 'public/passwords',
    registrations: 'public/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  namespace :admin do
    root to: 'homes#top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update, :destroy]
    # resources :sessions, only: [:new, :create, :destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end
  namespace :public, path:'' do
    root to: 'homes#top'
    get 'about'=> 'homes#about'
    post 'orders/information' => 'orders#information'
    get 'orders/complete' => 'orders#complete'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    get 'customers/my_page' => 'customers#show', as: 'my_page'
    # get 'url' => 'controller#action', as: '_path'
    patch 'customers/cancel' => 'customers#cancel'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    # resources :registrations, only: [:new, :create]
    # resources :sessions, only: [:new, :create, :destroy]
    resources :items, only: [:index, :show]
    resources :customers, only: [:edit, :update]
    resources :cart_items, only: [:index, :update, :destroy, :create]
    resources :orders, only: [:new, :complete, :create, :index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    # getやpatchをresourcesの上に持ってくる
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_code, :email, presence: true

  def active_for_authentication?
    super && (is_active == true)
  end



end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end
  def show
    @customer = Customer.find(params[:id])
    @new_customer = Customer.new
  end
  def edit
    # @customer = current_customer
    @customer = Customer.find(params[:id])
  end
  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer)
    else
      render action: :edit
    end
  end
  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_code, :email)
    # (item_params)とアクションの後ろにつけることでrequireのpermit(カラム)を変更したりできる
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class='container px-5 px-sm-0'>
 <div class='row'>
  <div class="col-md-8 offset-md-1 mx-auto">
   <br></br>
   <h1>会員情報編集</h1>
   <% if @customer.errors.any? %>
    <%= @customer.errors.count %>件のエラーが発生しました
    <% @customer.errors.full_messages.each do |message| %>
     <%= message %>
    <% end %>
   <% end %>
   <%= form_with model: @customer, url:admin_customer_path, method: :patch, local:true do |customer| %>
   <table>
    <tr><th>会員ID</th><td><%= @customer.id %></td></tr>
    <tr><th>氏名</th><td><%= customer.text_field :last_name %></td><td><%= customer.text_field :first_name %></td></tr>
    <tr><th>フリガナ</th><td><%= customer.text_field :last_name_kana %></td><td><%= customer.text_field :first_name_kana %></td></tr>
    <tr><th>郵便番号</th><td><%= customer.text_field :postal_code %></td></tr>
    <tr><th>住所</th><td><%= customer.text_field :address %></td></tr>
    <tr><th>電話番号</th><td><%= customer.text_field :telephone_code %></td></tr>
    <tr><th>メールアドレス</th><td><%= customer.text_field :email %></td></tr>
    <tr>
     <th>会員ステータス</th>
     <td>
      <%= customer.radio_button :is_active, true %><%= customer.label :is_active, '有効', value: true %>
      <%= customer.radio_button :is_active, false %><%= customer.label :is_active, '退会', value: false %>
     </td>
    </tr>
   </table>
   <%= customer.submit "変更を保存" , class: "fas fa-user-cog btn btn-success" %>
   <% end %>
  </div>
 </div>
</div>

app/views/admin/customers/index.html.erb
<div class='container px-5 px-sm-0'>
 <div class='row'>
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
   <br></br>
   <h1>会員一覧</h1>
   <table class="table table-hover">
    <thead>
     <tr bgcolor="silver">
      <th>会員ID</th>
      <th>氏名</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
     </tr>
    </thead>
    <tbody>
     <% @customers.each do |customer| %>
     <tr>
      <td><%= customer.id %></td>
      <td><%= link_to customer.last_name + customer.first_name, admin_customer_path(customer.id) %></td>
      <td><%= customer.address %></td>
      <td>
       <% if customer.is_active %><p class="text-success">有効</p>
       <% else %><p class="text-secondary">退会</p>
       <% end %>
     </tr>
     <% end %>
    </tbody>
   </table>
  </div>
 </div>
</div>

app/views/admin/customers/show.html.erb
<div class='container'>
 <div class='row'>
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
   <br></br>
   <h1>会員詳細</h1>
   <table border="1">
    <tr><th bgcolor="silver">会員ID</th><td><%= @customer.id %></td></tr>
    <tr><th bgcolor="silver">氏名</th><td><%= @customer.last_name + @customer.first_name %></td></tr>
    <tr><th bgcolor="silver">フリガナ</th><td><%= @customer.last_name_kana + @customer.first_name_kana %></td></tr>
    <tr><th bgcolor="silver">郵便番号</th><td>〒<%= @customer.postal_code %></td></tr>
    <tr><th bgcolor="silver">住所</th><td><%= @customer.address %></td></tr>
    <tr><th bgcolor="silver">電話番号</th><td><%= @customer.telephone_code %></td></tr>
    <tr><th bgcolor="silver">メールアドレス</th><td><%= @customer.email %></td></tr>
    <tr><th bgcolor="silver">会員ステータス</th><td><% if @customer.is_active %>有効<% else %>退会<% end %></td></tr>
   </table>
   <%= link_to "編集する", edit_admin_customer_path(@customer.id), class: "fas fa-user-cog btn btn-success" %>
   <%= link_to "注文履歴一覧に戻る", admin_root_path, class: "fas fa-user-cog btn btn-primary" %>
  </div>
 </div>
</div>