config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
  }
  devise_for :customers, controllers: {
    sessions: 'public/sessions',
    passwords: 'public/passwords',
    registrations: 'public/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  namespace :admin do
    root to: 'homes#top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update, :destroy]
    # resources :sessions, only: [:new, :create, :destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end
  namespace :public, path:'' do
    root to: 'homes#top'
    get 'about'=> 'homes#about'
    post 'orders/information' => 'orders#information'
    get 'orders/complete' => 'orders#complete'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    get 'customers/my_page' => 'customers#show', as: 'my_page'
    # get 'url' => 'controller#action', as: '_path'
    patch 'customers/cancel' => 'customers#cancel'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    # resources :registrations, only: [:new, :create]
    # resources :sessions, only: [:new, :create, :destroy]
    resources :items, only: [:index, :show]
    resources :customers, only: [:edit, :update]
    resources :cart_items, only: [:index, :update, :destroy, :create]
    resources :orders, only: [:new, :complete, :create, :index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    # getやpatchをresourcesの上に持ってくる
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  validates :name, :postal_code, :address, presence: true

  def address_info
    [postal_code, address, name].join(' ')
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_code, :email, presence: true

  def active_for_authentication?
    super && (is_active == true)
  end



end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

  validates :image, :name, :introduction, :genre_id, :price, presence: true

  attachment :image
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer

  enum payment_method: { クレジットカード: 0, 銀行振込: 1, }
  enum status: { 入金待ち: 0, 入金確認: 1, 制作中: 2, 発送準備中: 3, 発送済み: 4, }

  # validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_code, :email, presence: true
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order

  enum making_status: { 着手不可: 0, 制作待ち: 1, 制作中: 2, 制作完了: 3, }

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end
  def create
    @genres = Genre.all
    @genre = Genre.new(genre_params)
    if @genre.save
    flash[:notice] = '投稿しました'
    redirect_to admin_genres_path
    # noticeはredirect_toの前に書く
    else
    @genres = Genre.all
    render action: :index
    # createを設定する時はストロングパラメータとsaveとredirect先がセット
    end
  end
  def edit
    @genre = Genre.find(params[:id])
  end
  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
    flash[:notice] = '保存しました'
    redirect_to admin_genres_path
    else
     render action: :edit
    # redirect_to(成功)とrender(失敗)した時の飛ぶ場所は同じでもいい
    end
    # rails routesでupdateを見るとputchとputが出るがこの違いは？
  end
  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end
  def new
    @item = Item.new
  end
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render action: :new
    end
  end
  def show
    @item = Item.find(params[:id])
    # (params[:id])はrails routesでidが記載されてあるものはつける
    # form_withなどがない場合はつけなくていい
    @new_item = Item.new
  end
  def edit
    @item = Item.find(params[:id])
  end
  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
     redirect_to admin_item_path(@item.id)
    else
      render action: :edit
    end
  end
  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to admin_items_path
  end
  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
    # (item_params)とアクションの後ろにつけることでrequireのpermit(カラム)を変更したりできる
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
  end
  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to admin_order_path(@order)
    @order_details = @order.order_details
    if @order.status == '入金確認'
      @order_details.each do |order_details|
        order_details.update(making_status:1)
      end
    end
  end
  private
  def order_params
    params.require(:order).permit(:status)
  #   # (item_params)とアクションの後ろにつけることでrequireのpermit(カラム)を変更したりできる
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # def after_sign_up_path_for(resource)
  #   customers_customers_my_page_path
  # end

  def after_sign_up_path_for(resource)
    byebug
    case resource
    # deviseを複数作っているときはcase resourceで場合分けをする
    when Admin
      new_admin_session_path
    when Customer
      public_my_page_path
    end
  end

  def after_sign_out_path_for(resource)
    case
    #sign_outの時はdeleteメゾット機能が反映され空の状態になっているのでresource入らない
    when Admin
      new_admin_session_path
    when Customer
      public_root_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_code, :password_confirmation])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class='container px-5 px-sm-0'>
 <div class='row'>
  <div class="col-md-8 offset-md-1 mx-auto">
   <br></br>
   <h1>ジャンル編集</h1>
   <% if @genre.errors.any? %>
    <div class="alert alert-warning">
     <ul>
      <% @genre.errors.full_messages.each do |message| %>
       <li><%= message %></li>
      <% end %>
     </ul>
    </div>
   <% end %>
   <%= form_with model: @genre, url: admin_genre_path , local:true do |genre| %>
   <p>ジャンル名 <%= genre.text_field :name %> <%= genre.submit '変更を保存',class: 'btn btn-success' %></p>
   <% end %>
  </div>
 </div>
</div>

app/views/admin/genres/index.html.erb
<div class='container'>
 <div class='row'>
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
   <br></br>
   <h1>ジャンル一覧・追加</h1>
   <% if @genre.errors.any? %>
   <% if @genre.name.blank? %><p class='text-danger'>※ジャンル名を登録してください</p><% else %><p class='text-danger'>※そのジャンル名は登録済みです</p><% end %>
  <% end %>
   <%= form_with model: @genre, url:admin_genres_path , local:true do |genre| %>
    <p>ジャンル名 <%= genre.text_field :name %> <%= genre.submit "新規登録" , class: "fas fa-user-cog btn btn-success" %></p>
    <%= flash[:notice] %>
    <br></br>
    <table class="table table-hover">
     <tr bgcolor="silver"><th>ジャンル</th><td></td></tr>
     <% @genres.each do |genre| %>
     <tr>
      <th><%= genre.name %></th>
      <td><%= link_to "編集する", edit_admin_genre_path(genre), class: "fas fa-user-cog btn btn-success" %></td>
     </tr>
     <% end %>
    </table>
    <% end %>
   </div>
  </div>
 </div>

app/views/admin/items/edit.html.erb
<div class='container px-5 px-sm-0'>
 <div class='row'>
  <div class="col-md-8 offset-md-1 mx-auto">
   <br></br>
   <h1>商品編集</h1>
   <% if @item.errors.any? %>
    <%= @item.errors.count %>件のエラーが発生しました
    <% @item.errors.full_messages.each do |message| %>
     <%= message %>
    <% end %>
   <% end %>
   <%= form_with model: @item, url:admin_item_path(@item) , local:true do |item| %>
    <table>
     <tr><th>商品画像</th><td><%= item.attachment_field :image %></td></tr>
     <tr><th>商品名</th><td><%= item.text_field :name, class: "form-control" %></td></tr>
     <tr><th>商品説明</th><td><%= item.text_area :introduction, class: "form-control" %></td></tr>
     <tr><th>ジャンル</th><td><%= item.collection_select :genre_id, Genre.all, :id, :name %></td></tr>
     <tr><th>税抜価格</th><td><%= item.number_field :price, class: "form-control" %></td><td>円</td></tr>
     <tr>
      <th>販売ステータス</th>
      <td>
       <%= item.radio_button :is_active, true %>
       <%= item.label :is_active, '販売中', value: true %>
       <%= item.radio_button :is_active, false %>
       <%= item.label :is_active, '販売停止中', value: false %>
      </td>
      <td><%= item.submit "変更を保存" , class: "fas fa-user-cog btn btn-success" %></td>
     </tr>
    </table>
   <% end %>
  </div>
 </div>
</div>

app/views/admin/items/index.html.erb
<div class='container px-5 px-sm-0'>
 <div class='row'>
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
   <br></br>
   <h1>商品一覧</h1>
   <%= link_to "商品新規登録" ,new_admin_item_path, class: "fas fa-user-cog btn btn-success" %>
   <table class="table table-hover">
    <thead>
     <tr bgcolor="silver">
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
     </tr>
    </thead>
    <tbody>
     <% @items.each do |item| %>
     <tr>
      <td><%= item.id  %></td>
      <td>
       <%= link_to item.name, admin_item_path(item.id) %>
      </td>
      <td><%= item.price %>円</td>
      <td><%= item.genre.name  %></td>
      <td>
       <% if item.is_active %><p class="text-success">販売中</p>
       <% else %><p class="text-secondary">販売停止中</p>
       <% end %>
      </td>
     </tr>
     <% end %>
    </tbody>
   </table>
  </div>
 </div>
</div>

app/views/admin/items/new.html.erb
<div class='container px-5 px-sm-0'>
 <div class='row'>
  <div class="col-md-8 offset-md-1 mx-auto">
   <br></br>
   <h1>商品新規登録</h1>
   <% if @item.errors.any? %>
    <%= @item.errors.count %>件のエラーが発生しました
    <% @item.errors.full_messages.each do |message| %>
     <%= message %>
    <% end %>
   <% end %>
   <%= form_with model: @item, url:admin_items_path , local:true do |item| %>
   <!--form_withはtableの外trのうちに入れる-->
   <table>
    <tr><th>商品画像</th><td><%= item.attachment_field :image %></td></tr>
    <tr><th>商品名</th><td><%= item.text_field :name, class: "form-control" %></td></tr>
    <tr><th>商品説明</th><td><%= item.text_area :introduction, class: "form-control" %></td></tr>
    <tr><th>ジャンル</th><td><%= item.collection_select :genre_id, Genre.all, :id, :name %></td></tr>
    <tr><th>税抜価格</th><td><%= item.number_field :price, class: "form-control" %></td><td>円</td></tr>
    <tr>
     <th>販売ステータス</th>
     <td>
       <%= item.radio_button :is_active, true %><%= item.label :is_active, '販売中', value: true %>
       <%= item.radio_button :is_active, false %><%= item.label :is_active, '販売停止中', value: false %>
     </td>
     <td><%= item.submit "新規登録" , class: "fas fa-user-cog btn btn-success"%></td>
    </tr>
   </table>
   <% end %>
  </div>
 </div>
</div>

app/views/admin/items/show.html.erb
<div class='container'>
 <div class='row'>
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
   <br></br>
   <h1>商品詳細</h1><%= attachment_image_tag @item, :image,size: '100x100' %>
   <table>
    <tr><th>商品名</th><td><%= @item.name %></td></tr>
    <tr><th>商品説明</th><td><%= @item.introduction %></td></tr>
    <tr><th>ジャンル</th><td><%= @item.genre.name %></td></tr>
    <tr><th>税込価格</br>(税抜価格)</th><td><%= (@item.price* 1.1).round %>円<br>(<%= @item.price %>円)</td></tr>
    <tr><th>販売ステータス</th><td><% if @item.is_active %>販売中<% else %>販売停止中<% end %></td></tr>
    <!--each doは複数の時に使うのでコントローラのshowアクションからそのまま引っ張ってくるために％の中に＠をつけている-->
   </table>
   <%= link_to "編集する" ,edit_admin_item_path, class: "fas fa-user-cog btn btn-success" %>
  </div>
 </div>
</div>

app/views/admin/orders/show.html.erb
<div class='container px-5 px-sm-0'>
 <div class='row'>
  <div class="col-md-8 offset-md-1">
   <h1>注文履歴詳細</h1>
   <table border="1">
    <tr>
     <th bgcolor="silver">購入者</th>
     <td><%= link_to @order.customer.last_name + @order.customer.first_name, admin_customer_path(@order.customer.id), class: 'hoge' %></td>
    </tr>
    <tr>
     <th bgcolor="silver">注文日</th>
     <td><%= @order.created_at.strftime("%Y/%-m/%-d") %></td>
    </tr>
    <tr>
     <th bgcolor="silver">配送先</th>
     <td>〒<%= @order.postal_code %><br><%= @order.address %><br><%= @order.name %></td>
    </tr>
    <tr>
     <th bgcolor="silver">支払方法</th>
     <td><%= @order.payment_method %></td>
    </tr>
    <tr>

     <th bgcolor="silver">注文ステータス</th>
     <td>
      <%= form_with model: @order, url: admin_order_path, local: true do |order| %>
      <%= order.select :status, Order.statuses.keys %>
      <%= order.submit "更新" , class: "fas fa-user-cog btn btn-success" %>
      <% end %>
     </td>

    </tr>
   </table>
   <br></br>
   <table border="1">
    <thead>
     <tr bgcolor="silver">
      <th>商品名</th>
      <th>単価(税込)</th>
      <th>数量</th>
      <th>小計(税込)</th>
      <th>製作ステータス</th>
      <th></th>
     </tr>
    </thead>
    <tbody>
      <% @order.order_details.each do |f| %>
      <tr>
      <td><%= f.item.name %></td>
      <td>¥<%= f.item.price %>円(¥<%= (f.item.price* 1.1).round %>円)</td>
      <td><%= f.amount %></td>
      <td>¥<%= f.item.price* f.amount %>円(¥<%= f.price %>円)</td>
      <td>
       <%= form_with model: f, url: admin_order_detail_path(f), local: true do |order| %>
        <%= order.select :making_status, OrderDetail.making_statuses.keys %>
        <%= order.submit "更新" , class: "fas fa-user-cog btn btn-success" %>
       <% end %>
      </td>
     </tr>
     <% end %>
    </tbody>
   </table>
   <table border="1">
    <tr>
     <th bgcolor="silver">商品合計</th>
     <td><%= @order.total_payment - @order.shipping_cost %></td>
    </tr>
    <tr>
     <th bgcolor="silver">送料</th>
     <td><%= @order.shipping_cost %></td>
    </tr>
    <tr>
     <th bgcolor="silver">請求金額合計</th>
     <td><%= @order.total_payment %></td>
    </tr>
   </table>
  </div>
 </div>
</div>