config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
  }
  devise_for :customers, controllers: {
    sessions: 'public/sessions',
    passwords: 'public/passwords',
    registrations: 'public/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  namespace :admin do
    root to: 'homes#top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update, :destroy]
    # resources :sessions, only: [:new, :create, :destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end
  namespace :public, path:'' do
    root to: 'homes#top'
    get 'about'=> 'homes#about'
    post 'orders/information' => 'orders#information'
    get 'orders/complete' => 'orders#complete'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    get 'customers/my_page' => 'customers#show', as: 'my_page'
    # get 'url' => 'controller#action', as: '_path'
    patch 'customers/cancel' => 'customers#cancel'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    # resources :registrations, only: [:new, :create]
    # resources :sessions, only: [:new, :create, :destroy]
    resources :items, only: [:index, :show]
    resources :customers, only: [:edit, :update]
    resources :cart_items, only: [:index, :update, :destroy, :create]
    resources :orders, only: [:new, :complete, :create, :index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    # getやpatchをresourcesの上に持ってくる
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  validates :name, :postal_code, :address, presence: true

  def address_info
    [postal_code, address, name].join(' ')
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_code, :email, presence: true

  def active_for_authentication?
    super && (is_active == true)
  end



end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

  validates :image, :name, :introduction, :genre_id, :price, presence: true

  attachment :image
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer

  enum payment_method: { クレジットカード: 0, 銀行振込: 1, }
  enum status: { 入金待ち: 0, 入金確認: 1, 制作中: 2, 発送準備中: 3, 発送済み: 4, }

  # validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_code, :email, presence: true
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order

  enum making_status: { 着手不可: 0, 制作待ち: 1, 制作中: 2, 制作完了: 3, }

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end
  def new
    @item = Item.new
  end
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render action: :new
    end
  end
  def show
    @item = Item.find(params[:id])
    # (params[:id])はrails routesでidが記載されてあるものはつける
    # form_withなどがない場合はつけなくていい
    @new_item = Item.new
  end
  def edit
    @item = Item.find(params[:id])
  end
  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
     redirect_to admin_item_path(@item.id)
    else
      render action: :edit
    end
  end
  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to admin_items_path
  end
  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
    # (item_params)とアクションの後ろにつけることでrequireのpermit(カラム)を変更したりできる
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # def after_sign_up_path_for(resource)
  #   customers_customers_my_page_path
  # end

  def after_sign_up_path_for(resource)
    byebug
    case resource
    # deviseを複数作っているときはcase resourceで場合分けをする
    when Admin
      new_admin_session_path
    when Customer
      public_my_page_path
    end
  end

  def after_sign_out_path_for(resource)
    case
    #sign_outの時はdeleteメゾット機能が反映され空の状態になっているのでresource入らない
    when Admin
      new_admin_session_path
    when Customer
      public_root_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_code, :password_confirmation])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  　<header>
    　<nav class="navbar navbar-expand-lg navbar-dark bg-info">
        <div class="container">
          <a class="navbar-brand" href="/"><span>NaganoCake</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <% if customer_signed_in? %>
            <!--#顧客がログインした場合-->
              <ul class="navbar-nav ml-auto">
                <li><%= link_to "マイページ" ,public_my_page_path, class: "fas fa-home nav-link text-light" %></li>
                <li><%= link_to "商品一覧" ,public_items_path, class: "fas fa-home nav-link text-light" %></li>
                <li><%= link_to "カート" ,public_cart_items_path, class: "fas fa-home nav-link text-light" %></li>
                <li><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "fas fa-home nav-link text-light" %></li>
              </ul>
            <% elsif admin_signed_in? %>
            <!--#管理者がログインした場合-->
              <ul class="navbar-nav ml-auto">
                <li><%= link_to "商品一覧", admin_items_path, class: "fas fa-home nav-link text-light" %></li>
                <li><%= link_to "会員一覧", admin_customers_path, class: "fas fa-home nav-link text-light" %></li>
                <li><%= link_to "注文履歴一覧", admin_root_path, class: "fas fa-home nav-link text-light" %></li>
                <li><%= link_to "ジャンル一覧", admin_genres_path, class: "fas fa-home nav-link text-light" %></li>
                <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "fas fa-home nav-link text-light" %></li>
              </ul>
            <% else %>
            <!--#どちらにもログインしていない場合-->
            <ul class="navbar-nav ml-auto">
              <li><%= link_to "about", public_about_path, class: "fas fa-home nav-link text-light" %></li>
              <li><%= link_to "商品一覧", public_items_path, class: "fas fa-home nav-link text-light"%></li>
              <li><%= link_to "新規登録", new_customer_registration_path, class: "fas fa-home nav-link text-light"%></li>
              <li><%= link_to "ログイン", new_customer_session_path, class: "fas fa-home nav-link text-light" %></li>
            </ul>
            <% end %>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
    <!--yieldは他のhtmlを持ってくる機能-->
  </body>
</html>